routes/web.php
<?php
use App\Http\Controllers\PrincipalController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [PrincipalController::class, 'principalBaterias']  )->name('/');

Route::get('/teoria', [PrincipalController::class, 'teoria']  )->name('teoria');

Route::get('/procedimento', [PrincipalController::class, 'procedimento']  )->name('procedimento');

Route::get('/medicoes', [PrincipalController::class, 'medicoes']  )->name('medicoes');

Route::get('/conclusoes', [PrincipalController::class, 'conclusoes']  )->name('conclusoes');

Route::get('/principal', [PrincipalController::class, 'principal']  );


Route::get('/pagina1', [PrincipalController::class, 'pagina1']);
    

Route::get('/pagina2', [PrincipalController::class, 'pagina2']);
     

app/Models/Medicoes.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Medicoes extends Model
{
    use HasFactory;

    public function getResistenciaInternaAttribute(){
        return $this->resistencia_carga * ($this->tensao_sem_carga/$this->tensao_com_carga -1);
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/PrincipalController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Medicoes;

class PrincipalController extends Controller
{
    public function principalBaterias(){
        return view('principalBaterias');
    }
    public function teoria(){
        return view('teoria');
    }
    public function procedimento(){
        return view('procedimento');
    }
    public function medicoes(){
        $medicoes = Medicoes::all();
        return view('medicoes',compact('medicoes'));
    }
    public function conclusoes(){
        return view('conclusoes');
    }
   
    public function principal(){
        return view('principal');
    }
    public function pagina1(){
        return view('pagina1');
    }
    public function pagina2(){
        return view('pagina2');
    }
}

resources/views/conclusoes.blade.php
@extends('templates.base')

@section('conteudo')
    
    <main>

       <h1> Conclusão:</h1> <hr>

Através da nossa prática conseguimos os valores das resistências internas das pilhas/baterias(r), fonte de tensão real(E), a queda de tensão externa (VR) e a corrente presente em cada bateria que é possível conferir o valor do 'r' através do site. Além de ser possível calcular se as pilhas/baterias estão ou não em seu tempo útil de vida.

<br><br>
<img class="conclusao2" src="../imgs/conclusao2.jpeg"  alt="../bateria">

</p>
        <p>

        </p>
        
    </main>

    @endsection

    @section('rodape')
    
    <h4>Rodape da pagina principal</h4>
    
    @endsection

resources/views/medicoes.blade.php
@extends('templates.base')

@section('conteudo')
    <main>
        <h1>Medições</h1>
        <hr>
        <h2>Resultados:</h2>
        <table class="table table-dark table-striped table-bordered" id="tbDados">
                <\<thead>
               <tr>
                <th>Pilha/bateria</th>
                <th>Tensao nominal(v)</th>
                <th>Capacidade de corrente (mA.h)</th>
                <th>Tensao sem carga(v)</th>
                <th>Tensao com carga(v)</th>
                <th>Resistência de carga(ohm)</th>
                <th>Resistencia interna(ohm)</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($medicoes as $medicao)
                    <tr>
                        <td>{{$medicao->pilha_bateria}}</td>
                        <td>{{number_format($medicao->tensao_nominal,1,'.','')}}</td>
                        <td>{{$medicao->capacidade_corrente}}</td>
                        <td>{{$medicao->tensao_sem_corrente}}</td>
                        <td>{{$medicao->tensao_com_corrente}}</td>
                        <td>{{$medicao->resistencia_carga}}</td>
                        <td>{{number_format($medicao->resistencia_interna,3,'.','')}}</td>
                    </tr>    
                    @endforeach
                </tbody>
        </table>
    </main>
    @endsection

    @section('rodape')
    
    <h4>Rodape da pagina principal</h4>
    
    @endsection

resources/views/pagina1.blade.php
@extends('templates.base')

@section('conteudo')
    <h1>Pagina 1 </h1>
    
@endsection

@section('rodape')

<h4>Rodape da pagina 1</h4>

@endsection

resources/views/pagina2.blade.php
@extends('templates.base')

@section('conteudo')
    <h1>Pagina 2 </h1>
   
@endsection

@section('rodape')

<h4>Rodape da pagina 2</h4>

@endsection

resources/views/principal.blade.php
@extends('templates.base')

@section('conteudo')
    <h1>Pagina principal</h1>
    
@endsection

@section('rodape')

<h4>Rodape da pagina principal</h4>

@endsection

resources/views/principalBaterias.blade.php
@extends('templates.base')

@section('conteudo')
    <main>

        <h1>turma: 2D2 - Grupo 1</h1>
        <h2>participantes</h2>
        <hr>
        <table class="table table-stripedd table-bordered">
            <tr>
                <th>matricula</th>
                <th>nome</th>
                <th>função</th>
            </tr>  
            <tr>
                <td>0073587</td>
                <td>Ana Gabriela</td>
                <td>gerente</td>
            </tr> 
            <tr>
                <td>0072531</td>
                <td>Ana julia</td>
                <td>Medidor</td>
            </tr> 
            <tr>
                <td>0073004</td>
                <td>Camila Bicalho</td>
                <td>Medidor</td>
            </tr> 
            <tr>
                <td>0066682</td>
                <td>Iara Geralda</td>
                <td>Medidor</td>
            </tr> 
            <tr>
                <td>0072541</td>
                <td>Nicolas Aniceto</td>
                <td>Programação</td>
            </tr>
        </table>
        
        <img class="grupo"src="../imgs/grupo.jpeg"  alt="../bateria"> 
    </main>
    
 @endsection

@section('rodape')
<h4>Rodape da pagina principal</h4>
@endsection

resources/views/procedimento.blade.php
<!DOCTYPE html>
<html lang="pt-br">
<head>
   
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  <link rel="stylesheet"  href="../css/estilos.css"> 
</head>
<body>
   <header>
        <h1>baterias</h1>
   </header>
    <nav>
     <ul>

     <li><a  href="../index.html">Voltar para a pgaina principal</a></li>
     

     </ul>
    </nav>
    <main>
        <h1>procedimentos</h1> 
            <hr>
        Inicialmente nos dividimos em duas partes para fazermos as medições utilizando a determinação da Resistência Interna de Fontes de Tensão (pilhas e baterias), com um multimetro enquanto os demais realizavam a crianção do site. Com isso fomos capazes de realizar a medição das 10 baterias e descobri o valor da corrente interna(também considerada como 'r') e metade do site já estava pronto. Nos próximos dias o grupo todo principalmente nosso programador focamos no termino da montagem do site, assim no próximo dia ficamos totalmente focados em realizar as finalizações do site juntamente com o envio de dados das bateria do site para finalmente estar completo!
         <hr>
        <img class="conclusao" src="../imgs/conclusao.jpeg"  alt="../bateria">
        
    </p>
        <p>

        </p>
        
    </main>

</body>
</html>

resources/views/templates/base.blade.php
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AulaLaravel</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="{{asset('css/estilos.css') }}"> 
</head>
<body> 
    <div class="container-md">
    <h1>Aula de Laravel</h1>
    <hr>
    <nav>
        <ul>
       <li><a href="{{ route('/') }}">inicio</a></li>      
       <li><a href="{{ route('teoria') }}">teoria</a></li> 
       <li><a href="{{ route('procedimento') }}">procedimento</a></li>  
       <li><a href="{{ route('medicoes') }}">Medições</a></li> 
       <li><a href="{{ route('conclusoes') }}">Conclusões</a></li> 
   </ul>
   </nav>    
    @yield("conteudo")
    <hr>
    @yield("rodape")
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</div>
</body>
</html>

resources/views/teoria.blade.php
    @extends('templates.base')

@section('conteudo')
    <main>

        <h1>teoria</h1>
        <h2>descrição das pilhas</h2>
        <hr>
        <hr>
            <h3>O que é uma pilha/bateria?</h3>
 As pilhas e baterias são dispositivos que armazenam energia em formato químico e a transforma em energia elétrica quando são utilizadas em um circuito. Embora possuam algumas diferenças em sua construção e uso, ambos têm uma estrutura básica semelhante, composta por alguns elementos principais:<br><br>
1.	Cátodo: É o lado positivo que ocorre reações químicas de redução durante o funcionamento do dispositivo.<br>
2.	Ânodo: É o eletrodo negativo que ocorre as reações químicas de oxidação durante o funcionamento do dispositivo.<br>
3.	Eletrólito: É uma substância condutora que permite o fluxo de cargas elétricas entre o cátodo e o ânodo. O eletrólito pode ser líquido, sólido ou gel.<br>
4.	Separador: É uma barreira física ou membrana que impede o contato direto entre o cátodo e o ânodo, evitando curtos-circuitos e garantindo a eficiência do dispositivo.<br>
5.	Caixa ou invólucro: É a estrutura que envolve e protege os componentes internos da pilha ou bateria.<br>
<br>
Os materiais específicos utilizados nos componentes variam dependendo do tipo de pilha ou bateria. Alguns dos tipos mais comuns incluem:<br>
- Pilhas alcalinas: utilizam zinco como ânodo e dióxido de manganês como cátodo, com um eletrólito alcalino (geralmente hidróxido de potássio).<br>
- Pilhas de zinco-carbono: similares às alcalinas, mas com um eletrólito mais ácido (geralmente cloreto de amônio).<br>
- Baterias de íon-lítio: amplamente usadas em dispositivos eletrônicos portáteis, como celulares e laptops. O cátodo é composto por óxido de lítio e cobalto, o ânodo por grafite e o eletrólito por sais de lítio dissolvidos em solventes orgânicos.<br>
- Baterias de chumbo-ácido: usadas em veículos automotores e sistemas de energia em alguns casos. Possuem placas de chumbo no ânodo e no cátodo, e o eletrólito é uma solução de ácido sulfúrico.<br>
- Baterias de níquel-cádmio: embora menos comuns atualmente, utilizavam cádmio no ânodo, óxido de níquel no cátodo e um eletrólito alcalino.<br>
<br>
<img class="bateria"src="../imgs/bateria.jpeg"  alt="../bateria"> 
<br>
<hr>
<h3>Teoria do trabalho</h3>
O trabalho tem como objetivo calcular a resistência interna de uma fonte de tensão real.<br>
Uma fonte de tensão real é constituída de uma fonte de tensão ideal (E) em série com a sua resistência interna para sabermos é necessário conhecer a tensão interna fonte sem carga ligada e quando conectada com a carga  mostrando que a corrente que circulará vai produzir a queda de tensão interna (Vr) e a queda de tensão externa (VR).
Usando a equação do divisor ,podemos medir indiretamente  a resistência de uma pilha ou baterias.<br>
<img class="circuito"src="../imgs/circuito.jpeg"  alt="../bateria"> <br>
<img class="equacao1"src="../imgs/equacao1.jpeg"  alt="../bateria"> 

    </main>
    @endsection

@section('rodape')

<h4>Rodape teoria</h4>

@endsection